name: flutter_route
description: Um gerenciador de rotas leve e intuitivo para aplicações Flutter.
version: 0.0.1
homepage: https://github.com/seu_usuario/flutter_route
repository: https://github.com/seu_usuario/flutter_route

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

