name: flutter_route
description: Um gerenciador de rotas leve e intuitivo para aplicações Flutter.
version: 0.0.2

homepage: https://github.com/Isac-Eugenio/flutter_route
repository: https://github.com/Isac-Eugenio/flutter_route

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  signals: ^7.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
